name: ğŸš€ Deploy to Server

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write  # Ğ”Ğ»Ñ GitHub Container Registry

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ§© Checkout
        uses: actions/checkout@v4
        
      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: ğŸ” Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: ğŸ“¦ Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bot_vpn:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: ğŸ§° Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: ğŸš€ Deploy to server
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}/bot_vpn:latest
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            docker stop bot_vpn || true
            docker rm bot_vpn || true
            docker pull $REGISTRY
            docker run -d --name bot_vpn --restart always $REGISTRY
          EOF
